[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "index.html"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

# Fix the hooks - remove the problematic pre_build hook and fix post_build
[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "if [ -f ./dist/index.html ]; then cp ./dist/index.html ./dist/404.html; fi",
]
