[build]
target = "index.html"
dist = "dist"
# Use root path for both development and production
public_url = "/"

[watch]
watch = ["src", "index.html"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

# GitHub Pages hooks (only used for production builds)
[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
    "-c",
    "if [ -f ./dist/index.html ]; then cp ./dist/index.html ./dist/404.html && touch ./dist/.nojekyll; fi",
]
