// The 'test_web5claimsleo' test program.
import web5claimsleo.aleo;
program test_web5claimsleo.aleo {
    @test
    script test_it() {
        let result: u32 = web5claimsleo.aleo/main(1u32, 2u32);
        assert_eq(result, 3u32);
    }

    @test
    @should_fail
    transition do_nothing() {
        let result: u32 = web5claimsleo.aleo/main(2u32, 3u32);
        assert_eq(result, 3u32);
    }
}
