name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: zkpass/package-lock.json

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            web5claims-ui -> target

      - name: Install trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Build main library
        run: cargo build --release

      - name: Build UI with trunk for GitHub Pages
        run: |
          cd web5claims-ui
          trunk build --release --public-url /

      - name: Install ZKPass dependencies
        run: |
          cd zkpass
          npm ci

      - name: Build ZKPass for GitHub Pages
        run: |
          cd zkpass
          NODE_ENV=production npm run build:github-pages

      - name: Create additional GitHub Pages files
        run: |
          cd web5claims-ui/dist
          # Create .nojekyll to bypass Jekyll processing
          touch .nojekyll
          # Ensure 404.html exists for SPA routing
          cp index.html 404.html
          # Copy ZKPass build to subfolder
          mkdir -p zkpass
          cp -r ../../zkpass/dist/* zkpass/

      - name: Debug ZKPass build
        run: |
          echo "=== ZKPass Build Debug ==="
          ls -la web5claims-ui/dist/zkpass/
          echo "=== Assets folder ==="
          ls -la web5claims-ui/dist/zkpass/assets/ || echo "No assets folder"
          echo "=== Index.html content ==="
          head -20 web5claims-ui/dist/zkpass/index.html || echo "No index.html"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web5claims-ui/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
